In [11]:
import sys
root_path = "/Users/sa/CS/stanford/cs229/Project/Neural-Response-Generator-augmented-with-psychological-personalities/"

import pandas as pd
import autoreload
import sys
sys.path.append(root_path + "library/")

%load_ext autoreload
%autoreload 2

# essentials
import numpy as np
from tqdm.notebook import tqdm
import pickle
import json

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Formating Movie data

In [179]:
import csv

with open('/Users/sa/Downloads/cornell/movie_conversations.txt', 'r') as f:
    content = [row.split(" +++$+++ ") for row in f.readlines()]
    
movie_conversation = pd.DataFrame(data=content, columns=["char1Id", "char2Id", "movieId", "lines"])

movie_conversation.to_csv("../../data/processed/final/movie_conversation.csv")

In [182]:
import csv

with open('/Users/sa/Downloads/cornell/movie_lines.txt', 'r', errors='replace') as f:
    #f.readlines()
    content = [row.split(" +++$+++ ") for row in f.readlines()]
    
movie_lines = pd.DataFrame(data=content, columns=["lineId", "charId", "movieId", "charName", "line"])

movie_lines.to_csv("../../data/processed/final/movie_lines.csv")

In [185]:
import csv

with open('/Users/sa/Downloads/cornell/movie_titles_metadata.txt', 'r', errors='replace') as f:
    #f.readlines()
    content = [row.split(" +++$+++ ") for row in f.readlines()]
    
movie_titles = pd.DataFrame(data=content, columns=["movieId", "movieTitle", "movieYr", "IMDBr", "IMDBv", "genres"])

movie_titles.to_csv("../../data/processed/final/movie_titles.csv")

In [306]:
movie_titles.sort_values(by='IMDBr',ascending=False)[:30]

,movieId,movieTitle,movieYr,IMDBr,IMDBv,genres
457,m457,neuromancer,1988,9.30,48,"['action', 'adventure', 'animation', 'sci-fi']\n"
203,m203,the godfather,1972,9.20,419312,"['crime', 'drama', 'thriller']\n"
369,m369,the godfather: part ii,1974,9.00,251290,"['crime', 'drama', 'thriller']\n"
504,m504,schindler's list,1993,8.90,282473,"['biography', 'drama', 'history', 'war']\n"
463,m463,one flew over the cuckoo's nest,1975,8.90,219739,['drama']\n
42,m42,casablanca,1942,8.80,170874,"['drama', 'romance', 'war']\n"
529,m529,star wars,1977,8.80,326619,"['action', 'adventure', 'fantasy', 'sci-fi']\n"
372,m372,goodfellas,1990,8.80,234582,"['crime', 'drama', 'thriller']\n"
348,m348,fight club,1999,8.80,391697,"['crime', 'drama', 'mystery', 'thriller']\n"
419,m419,the silence of the lambs,1991,8.70,251237,"['crime', 'thriller']\n"
402,m402,it's a wonderful life,1946,8.70,103290,"['drama', 'fantasy', 'romance']\n"
433,m433,the matrix,1999,8.70,389480,"['action', 'adventure', 'adventure', 'adventur..."
167,m167,rear window,1954,8.70,121165,"['crime', 'mystery', 'romance', 'thriller']\n"
592,m592,the usual suspects,1995,8.70,272137,"['crime', 'mystery', 'thriller']\n"
430,m430,manhunt,2003,8.70,736,"['action', 'adventure', 'crime', 'horror', 'th..."
436,m436,memento,2000,8.70,281027,"['crime', 'drama', 'mystery', 'thriller']\n"
539,m539,sunset blvd.,1950,8.70,55994,"['drama', 'film-noir']\n"
482,m482,psycho,1960,8.70,146915,"['drama', 'horror', 'mystery', 'thriller', 'th..."
298,m298,citizen kane,1941,8.60,140517,"['drama', 'mystery']\n"
114,m114,lï¿½on,1994,8.60,204901,"['crime', 'drama', 'thriller']\n"
247,m247,apocalypse now,1979,8.60,176465,"['drama', 'war']\n"
205,m205,taxi driver,1976,8.60,159525,"['drama', 'thriller']\n"
594,m594,vertigo,1958,8.60,93524,"['crime', 'mystery', 'romance', 'thriller']\n"
536,m536,dr. strangelove or: how i learned to stop worr...,1964,8.60,158529,"['comedy', 'drama']\n"
535,m535,stranglehold,2007,8.60,907,"['action', 'adventure', 'crime']\n"
514,m514,the shining,1980,8.50,182077,"['horror', 'mystery', 'thriller']\n"
502,m502,saving private ryan,1998,8.50,275666,"['action', 'drama', 'history', 'war']\n"
297,m297,nuovo cinema paradiso,1988,8.50,46801,"['comedy', 'drama', 'romance']\n"
566,m566,the pianist,2002,8.50,138080,"['biography', 'drama', 'war']\n"
301,m301,a clockwork orange,1971,8.50,197372,"['crime', 'drama', 'sci-fi']\n"

In [311]:
movie_script = movie_conversation.loc[movie_conversation['movieId'].isin(list(movie_titles.sort_values(by='IMDBr',ascending=False).movieId[:50]))].copy()

In [312]:
import ast

#movie_script['lines']
contexted = []
for itr, rows in tqdm(movie_script.iterrows(), total=movie_script.shape[0], mininterval=20):
    line_row = []
    for lineId in ast.literal_eval(rows.lines):
        line_row.append(movie_lines.loc[movie_lines['lineId']==lineId].line)
    tmp = []
    for i in line_row:
        for j in i:
            tmp.append(j[:-1])
    movie_script.at[itr, 'lines'] = tmp
    contexted.append(tmp)

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=7067.0), HTML(value='')))

In [313]:
movie_script.to_csv('../../data/intermediate/movie_script_elong.csv')

In [314]:
movie_script

,char1Id,char2Id,movieId,lines
1716,u228,u233,m15,"[This floor's freezing., Christ. I never saw ..."
1717,u228,u233,m15,"[Whoooah! No shit? I'm impressed., Let's go...."
1718,u228,u233,m15,"[Hey, 'Top.' What's the op?, Rescue mission. ..."
1719,u228,u233,m15,"[Movement!, Position?, Can't lock up..., Talk ..."
1720,u228,u231,m15,"[...that's better. Pan it around a bit., Awri..."
...,...,...,...,...
80414,u8765,u8767,m594,"[She died., How?, By her own hand. There are ..."
80415,u8766,u8767,m594,"[No, that's not it. Nothing like it., But you ..."
80416,u8766,u8767,m594,"[She'll be out in a moment., Now, Judy, it isn..."
80417,u8766,u8767,m594,"[Yes! That's it!, I thought so!]"
80418,u8766,u8767,m594,"[Oh, yes! It may need some slight alterations,..."